<a href="https://colab.research.google.com/github/OkiHeo/python_machine_learning/blob/master/ch2_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EB%B3%B8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

사칙연산

In [1]:
(1+2*3-4)/5

0.6

In [2]:
2**8

256

In [3]:
x=1
y=1/3
x+y

1.3333333333333333

In [7]:
print(type(x),type(y))

<class 'int'> <class 'float'>


In [8]:
x = 1/3
x
y = 2/3
y


0.6666666666666666

문자열과 수치를 함께 표시

In [9]:
print('x='+str(x))

x=0.3333333333333333


In [10]:
x=1/3
y=1/7
z=1/4
print('weight: {0} kg {1}kg {2}kg'.format(x, y, z))

weight: 0.3333333333333333 kg 0.14285714285714285kg 0.25kg


In [12]:
print('weight: {0:.3f}kg {1:.3f}kg {2:.3f}kg'.format(x, y, z))

weight: 0.333kg 0.143kg 0.250kg


# list

In [13]:
x=[1, 1, 2, 4, 5]
print(x)

[1, 1, 2, 4, 5]


In [14]:
s=['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))
print(s)

<class 'str'>
<class 'int'>
['SUN', 1, 'MON', 2]


In [15]:
a = [[1, 2, 3], [5, 6, 7]]
print(a)

[[1, 2, 3], [5, 6, 7]]


In [16]:
x=[1, 2, 3]
print(len(x))

3


In [19]:
y=range(5, 10)
print(type(y))
print(list(y))
print(type(list(y)))

<class 'range'>
[5, 6, 7, 8, 9]
<class 'list'>


In [20]:
a=(1)
print(type(a))
b=(1,)
print(type(b))

<class 'int'>
<class 'tuple'>


# if문

In [21]:
x=11
if x>10:
  print('x is ')
  print('        larger than 10.')
else:
  print('x is smaller than 11')

x is 
        larger than 10.


# for문

In [22]:
for i in [1, 2, 3]:
  print(i)
for i in range(3, 7, 2):
  print(i)

1
2
3
3
5


In [24]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
  num[i] = num[i]*3
print(num)

[6, 12, 18, 24, 30]


In [25]:
num=[2, 4, 6, 8, 10]
for i, n in enumerate(num):
  num[i] = n*2
print(num)

[4, 8, 12, 16, 20]


# 벡터

In [27]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [28]:
print(x)

[1 2 3]


In [29]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x+y)

[5 7 9]


In [30]:
type(x)

numpy.ndarray

In [31]:
x[0] = 8
print(x)

[8 2 3]


In [32]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(np.arange(4, 10))

[4 5 6 7 8 9]


In [37]:
a = np.arange(10)
b = np.arange(5, 15)
print(a+b)

[ 5  7  9 11 13 15 17 19 21 23]


# 행렬

In [40]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [41]:
print(type(x.shape))

<class 'tuple'>


In [39]:
print(x.shape)

(2, 3)


In [43]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 9
print(x)

[[1 2 3]
 [4 5 9]]


In [45]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [47]:
np.random.rand(20)

array([0.63444793, 0.59376726, 0.68156781, 0.52048412, 0.94561051,
       0.82415997, 0.16225999, 0.19084766, 0.02568032, 0.19530375,
       0.0580724 , 0.02686245, 0.017644  , 0.56497843, 0.52536116,
       0.42502817, 0.69618506, 0.10699665, 0.33042691, 0.80630982])

In [49]:
np.random.rand(2, 3)

array([[0.74380303, 0.29029885, 0.35658039],
       [0.25869059, 0.53869806, 0.83441483]])

In [48]:
np.random.randint(1, 10, 5)

array([1, 7, 8, 5, 2])

In [52]:
a = np.arange(10)
a = a.reshape(2, 5).copy()
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# 행렬의 사칙연산

In [56]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print('x+y\n', x+y)
print('x-y\n', x-y)
print('x*y\n', x*y)
print('x/y\n', x/y)

x+y
 [[ 5  5  5]
 [10 10 10]]
x-y
 [[3 3 3]
 [6 6 6]]
x*y
 [[ 4  4  4]
 [16 16 16]]
x/y
 [[4. 4. 4.]
 [4. 4. 4.]]


In [57]:
x = np.arange(5)
print(2*x)

[0 2 4 6 8]


In [58]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v)
print(w)
print(v.dot(w))

[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]
[[14 14]
 [32 32]]


# 슬라이싱

In [59]:
x = np.arange(10)
print(x)
print(x[:5])
print(x[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 2 4 6 8]


# 조건을 만족하는 데이터의 수정

In [63]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
print(x>3)

[False False False False  True  True  True]


In [64]:
print(x)
x[x>3] *=10
print(x)

[ 1  1  2  3  5  8 13]
[  1   1   2   3  50  80 130]


# help

In [65]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
        If array-like, must contain integer values
    size : int or tuple of ints, optional
        Output shape.  

# 함수

In [72]:
def my_func(x):
  print(x+10)
  print(x*2)
  return x

print('주어진 값: ', my_func(5))

15
10
주어진 값:  5


In [79]:
def my_func1(d):
    m = np.mean(d)
    s = np.std(d)
    return m, s

# 실행부
data = np.random.randint(100)
data_mean, data_std = my_func1(data)
print('mean: {0:3.2f}, std: {1:3.2f}'.format(data_mean, data_std))

mean: 20.00, std: 0.00


In [81]:
result = my_func1(data)
print(result)
print(type(result))
print('mean: {0:3.2f}, std: {1:3.2f}'.format(result[0], result[1]))

(20.0, 0.0)
<class 'tuple'>
mean: 20.00, std: 0.00


# 파일 저장

In [82]:
data = np.random.rand(10)
print(data)
np.save('data.npy', data)   # data 내용 파일로 저장
data= []    # data변수에 저장되어있던 데이터를 삭제한다.
print(data)
data = np.load('data.npy')
print(data)

[0.78649595 0.20022429 0.38863239 0.44387385 0.56229891 0.76832141
 0.00098621 0.84624038 0.12642187 0.263973  ]
[]
[0.78649595 0.20022429 0.38863239 0.44387385 0.56229891 0.76832141
 0.00098621 0.84624038 0.12642187 0.263973  ]


In [87]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
print(data1, data2)
np.savez('dataz.npz', d1 = data1, d2 = data2)   # 데이터를 파일에 저장
data1 = []
data2 = []
print(data1, data2)
outfile = np.load('dataz.npz')     # 저장한 데이터를 load
print(outfile.files)
data1 = outfile['d1']
data2 = outfile['d2']
print(data1, data2)

[1 2 3] [10 20 30]
[] []
['d1', 'd2']
[1 2 3] [10 20 30]
